// src/data.js
const flatData = [
  { name: 'Life (placeholder)', parent: null, rank:"root", age: 4000, image: 'images/DNA.png', info: '' },
  { name: 'Animals', parent: 'Life (placeholder)', rank:"kingdom", age: 650, image: 'images/animal.png', info:'info/animals.md' },
  { name: 'Sponges', parent: 'Animals', age: 544, image: 'images/sponge.png', info:'info/porifera.md' },

  { name: 'Eumetazoa', parent: 'Animals', age:600, image: '', info:'' },
  { name: 'Comb jellies', parent: 'Eumetazoa', age: 544, image: 'images/ctenophora.png', info:'' },
  
  { name: 'ParaHoxozoa', parent: 'Eumetazoa', age: 0, image: '', info:'' },
    { name: 'Placozoa', parent: 'ParaHoxozoa', age: 550, image: 'images/placozoa.png', info:'info/placozoa.md' },
    { name: 'Symmetry', parent: 'ParaHoxozoa', age: 0, image: '', info:'' },
    { name: 'Cnidaria', parent: 'Symmetry', rank:"phylum", age: 0, image: '', info:'' },
        { name: 'Anthozoa', parent: 'Cnidaria', age: 0, image: '', info:'' },
            { name: 'Hexacorallia', parent: 'Anthozoa', age: 0, image: '', info:'' },
                { name: 'Sea Anenomes', parent: 'Hexacorallia', age: 0, image: '', info:'' },
                { name: 'Stony Corals', parent: 'Hexacorallia', age: 0, image: '', info:'' },
            { name: 'Soft Corals', parent: 'Anthozoa', age: 0, image: 'images/sea_pen.png', info:'' },
        { name: 'Medusozoa', parent: 'Cnidaria', age: 0, image: '', info:'' },
    { name: 'Bilateria', parent: 'Symmetry',  rank:"clade I", age: 570, image: 'images/bilateria.png', info:'info/bilateria.md' },
        { name: 'Deuterostomia', parent: 'Bilateria',  rank:"super-phylum", age: 558, image: '', info:''  },
            { name: 'Xenambulacraria', parent: 'Deuterostomia', age: 0, image: '', info:''  },
                { name: 'Xenacoelomorpha', parent: 'Xenambulacraria', age: 0, image: 'images/xenoturbell.png', info:'info/xenacoelomorpha.md'  },
                    //{ name: 'Xenoturbella', parent: 'Xenacoelomorpha', age: 0, image: 'images/xenoturbell.png', info:''  },                      unnecessary, now within parent group
                { name: 'Ambulacraria', parent: 'Xenambulacraria', age: 533, image: 'images/ambulacraria.png', info:'info/ambulacraria.md'},
                    { name: 'Hemichordata', parent: 'Ambulacraria', age: 0, image: 'images/pterobranch.png', info:'info/hemichordata.md'  },
                    { name: 'Echinodermata', parent: 'Ambulacraria', rank:"phylum", age: 515, image: 'images/echinodermata.png', info:'info/echinodermata.md'  },
                        { name: 'Crinoidea', parent: 'Echinodermata', age: 487, image: 'images/crinoidea.png', info:''  },
                        { name: 'Eleutherozoa', parent: 'Echinodermata', age: 0, image: '', info:''  },
                            { name: 'Echinozoa', parent: 'Eleutherozoa', age: 487, image: '', info:''  },
                                { name: 'Sea urchins', parent: 'Echinozoa', age: 450, image: 'images/seaurchins.jpg', info:''  },
                                { name: 'Sea cucumbers', parent: 'Echinozoa', age: 470, image: 'images/seacumber.jpg', info:''  },
                            { name: 'Asterozoa', parent: 'Eleutherozoa', age: 488, image: 'images/Somasteroidea.jpg', info:''  },
                                { name: 'Starfish', parent: 'Asterozoa', age: 450, image: 'images/starfish.jpg', info:''  },
                                { name: 'Brittle stars', parent: 'Asterozoa', age: 486, image: 'images/brittlestar.png', info:''  },
            { name: 'Chordata', parent: 'Deuterostomia', rank:"phylum", age: 539, image: '', info:''  },
                { name: 'Vetulicolia', parent: 'Chordata', age: 520, ageEnd: 501, image: 'images/vetulicolia.jpg', info:'info/vetulicolia.md'  },
                { name: 'Cathaymyrus', parent: 'Chordata', age: 518, ageEnd: 0, image: 'images/cathay.png', info:''  },
                { name: 'Cephalochordates', parent: 'Chordata', age: 518, image: 'images/lancelet.png', info:''  },
                { name: 'Olfactores', parent: 'Chordata', age: 518, image: '', info:''  },
                    { name: 'Tunicates', parent: 'Olfactores', age: 518, image: 'images/tunicate.jpg', info:'info/tunicates.md'  },
                    { name: 'Craniates', parent: 'Olfactores', age: 0, image: '', info:''  },
                        { name: 'Myllokunmingia', parent: 'Craniates', age: 518, ageEnd: 0, image: 'images/mylo.png', info:''  },
                        { name: 'Vertebrates', parent: 'Craniates', age: 0, image: '', info:''  },
                            { name: 'Cyclostomi', parent: 'Vertebrates', age: 0, unnamed: true, image: '', info:''  },
                                { name: 'Hagfish', parent: 'Cyclostomi', age: 311, image: 'images/hagfish.jpg', info:''  },
                                { name: 'Lamprey', parent: 'Cyclostomi', age: 0, image: 'images/lamprey.jpg', info:''  },    
                            { name: 'PanGnathostomata', parent: 'Vertebrates', age: 0, image: '', info:''  },
                                { name: 'Heterostracomorphii', parent: 'PanGnathostomata',unnamed: true, age: 0, image: '', info:''  },
                                    { name: 'Astraspsis', parent: 'Heterostracomorphii', age: 467, ageEnd: 433, image: 'images/astraspis.jpg', info:''  },
                                    { name: 'Arandaspida', parent: 'Heterostracomorphii', age: 480, ageEnd: 455, image: 'images/arandaspida.jpg', info:''  },
                                    { name: 'Athenaegis', parent: 'Heterostracomorphii', age: 430, ageEnd: 0, image: 'images/athenaegis.jpg', info:''  },
                                    { name: 'Heterostraci', parent: 'Heterostracomorphii', age: 430, ageEnd: 359, image: 'images/heterostraci.jpg', info:'info/heterostraci.md'  },
                                { name: 'Thelodonti', parent: 'PanGnathostomata', age: 458, ageEnd: 359, image: 'images/thelodonti.png', info:''  },
                                { name: 'Pituriaspida', parent: 'PanGnathostomata', age: 393, ageEnd: 383, image: 'images/pituriaspida.jpg', info:''  },
                                { name: 'Osteostraci', parent: 'PanGnathostomata', age: 433, ageEnd: 359, image: 'images/osteostraci.png', info:''  },
                                { name: 'Placodermi', parent: 'PanGnathostomata', age: 0, image: '', info:''  },
                                    { name: 'Antiarcha', parent: 'Placodermi', age: 426, ageEnd: 359, image: 'images/antiarcha.jpg', info:''  },
                                    { name: 'Arthrodira', parent: 'Placodermi', age: 419, ageEnd: 359, image: 'images/arthrodira.jpg', info:'info/arthrodira.md'  },
                                    { name: 'CrownGnathostomata', parent: 'Placodermi',  rank:"clade II", age: 0, image: '', info:''  },
                                        { name: 'Cartilaginous fishes', parent: 'CrownGnathostomata',rank:"clade III", age: 0, image: '', info:''  },
                                            { name: 'Spiny "sharks"', parent: 'Cartilaginous fishes', age: 439, ageEnd: 284, image: '', info:''  },
                                            { name: 'Chondrichthyes', parent: 'Cartilaginous fishes', age: 0, image: '', info:''  },
                                                { name: 'Chimaeraformes', parent: 'Chondrichthyes', age: 421, image: 'images/chimera.png', info:''  },
                                                { name: 'Elasmobranchii', parent: 'Chondrichthyes', age: 419, image: '', info:''  },
                                                    { name: 'True rays', parent: 'Elasmobranchii', age: 0, image: '', info:''  },
                                                        { name: 'Electric rays', parent: 'True rays', age: 56, image: '', info:''  },
                                                        { name: 'Stingrays', parent: 'True rays', age: 145, image: 'images/stingrays.jpg', info:'info/stingrays.md'},
                                                    { name: 'True sharks', parent: 'Elasmobranchii', age: 0, image: '', info:''  },
                                                        { name: 'Squalomorphi', parent: 'True sharks', age: 170, image: '', info:'info/squalomorphi.md'},
                                                            { name: 'Frilled Sharks', parent: 'Squalomorphi', age: 90, image: 'images/frilled_shark.jpg', info:''  },
                                                            { name: 'Angel Sharks', parent: 'Squalomorphi', age: 164, image: 'images/angel shark.png', info:''  },
                                                            { name: 'Sawsharks', parent: 'Squalomorphi', age: 85, image: 'images/sawshark.png', info:''  },
                                                            { name: 'Dogfish sharks', parent: 'Squalomorphi', age: 154, image: 'images/dogfish shark.jpg', info:''  },
                                                        { name: 'Galeomorphi', parent: 'True sharks', age: 201, image: '', info:'info/galeomorphi.md'},
                                                            { name: 'Bullhead sharks', parent: 'Galeomorphi', age: 193, image: 'images/bullhead.jpg', info:''},
                                                            { name: 'Orectolobiformes', parent: 'Galeomorphi', age: 179, image: '', info:''},
                                                                { name: 'Wobbegong', parent: 'Orectolobiformes', age: 150, image: 'images/wobbegong.jpg', info:''},
                                                                { name: 'Zebra shark', parent: 'Orectolobiformes', age: 0, image: '', info:''},
                                                                { name: 'Whale shark', parent: 'Orectolobiformes', age: 20, image: '', info:''},
                                                            { name: 'Lamniformes', parent: 'Galeomorphi', age: 167, image: '', info:''},
                                                                { name: 'Catshark', parent: 'Lamniformes', age: 154, image: 'images/catshark.jpg', info:''},
                                                                { name: 'Tiger shark', parent: 'Lamniformes', age: 14, image: 'images/tiger shark.jpg', info:''},
                                                                { name: 'Hammerhead shark', parent: 'Lamniformes', age: 20, image: 'images/hammerhead shark.jpg', info:''},
                                                            { name: 'Carcharhiniformes', parent: 'Galeomorphi', age: 167, image: '', info:''},
                                                                { name: 'Goblin shark', parent: 'Carcharhiniformes', age: 0, image: '', info:''},
                                                                { name: 'Megamouth shark', parent: 'Carcharhiniformes', age: 0, image: '', info:''},
                                                                { name: 'Thresher shark', parent: 'Carcharhiniformes', age: 45, image: '', info:''},
                                                                { name: 'Basking shark', parent: 'Carcharhiniformes', age: 23, image: '', info:''},
                                                                { name: 'Megalodon', parent: 'Carcharhiniformes', age: 23, ageEnd: 4, image: '', info:''},
                                                                { name: 'Great white shark', parent: 'Carcharhiniformes', age: 0, image: '', info:''},
                                        { name: 'Bony fishes', parent: 'CrownGnathostomata',rank:"clade III", age: 0, image: '', info:''  },
                                            { name: 'Ray-finned fishes', parent: 'Bony fishes',rank:"clade IV", age: 425, image: '', info:''  },
                                                { name: 'Birchirs', parent: 'Ray-finned fishes', age: 100,  image: '', info:''  },
                                                { name: 'anon_1', parent: 'Ray-finned fishes', unnamed: true, age: 0,  image: '', info:''  },
                                                    { name: 'Sturgeons', parent: 'anon_1', age: 97, image: '', info:''  },
                                                    { name: 'anon_2', parent: 'anon_1', unnamed: true, age: 251,  image: '', info:''  },
                                                        { name: 'Gars', parent: 'anon_2', age: 152, image: '', info:''  },
                                                        { name: 'anon_3', parent: 'anon_2', unnamed: true, age: 0,  image: '', info:''  },
                                                            { name: 'Eels', parent: 'anon_3', age: 97, image: '', info:''  },
                                                            { name: 'anon_4', parent: 'anon_3', unnamed: true, age: 0,  image: '', info:''  },
                                                                { name: 'Otocephala', parent: 'anon_4', age: 230, image: '', info:''  },
                                                                        { name: 'anon_39', parent: 'Otocephala', unnamed: true, age: 155,  image: '', info:''  },
                                                                            { name: 'Anchovies', parent: 'anon_39', age: 0,  image: '', info:''  },
                                                                            { name: 'Herring', parent: 'anon_39', age: 0,  image: '', info:''  },
                                                                        { name: 'anon_40', parent: 'Otocephala', unnamed: true, age: 0,  image: '', info:''  },
                                                                            { name: 'anon_41', parent: 'anon_40', unnamed: true, age: 0,  image: '', info:''  },
                                                                                { name: 'Carp', parent: 'anon_41', age: 0,  image: '', info:''  },
                                                                                { name: 'Minnow', parent: 'anon_41', age: 0,  image: '', info:''  },
                                                                            { name: 'anon_42', parent: 'anon_40', unnamed: true, age: 0,  image: '', info:''  },
                                                                                { name: 'anon_43', parent: 'anon_42', unnamed: true, age: 0,  image: '', info:''  },
                                                                                    { name: 'Tetra', parent: 'anon_43', age: 0,  image: '', info:''  },
                                                                                    { name: 'Pirahna', parent: 'anon_43', age: 0,  image: '', info:''  },
                                                                                { name: 'anon_44', parent: 'anon_42', unnamed: true, age: 0,  image: '', info:''  },
                                                                                    { name: 'anon_45', parent: 'anon_44', unnamed: true, age: 0,  image: '', info:''  },
                                                                                        { name: 'Knifefish', parent: 'anon_45', age: 0,  image: '', info:''  },
                                                                                        { name: 'Electric eel', parent: 'anon_45', age: 0,  image: '', info:''  },
                                                                                    { name: 'Catfish', parent: 'anon_44', age: 100,  image: '', info:''  },
                                                                { name: 'anon_5', parent: 'anon_4', unnamed: true, age: 240,  image: '', info:''  },
                                                                    { name: 'Salamanderfish', parent:'anon_5', age: 0, image: '', info:''  },
                                                                    { name: 'anon_6', parent: 'anon_5', unnamed: true, age: 0,  image: '', info:''  },
                                                                        { name: 'Protacanthopterygii', parent: 'anon_6', age: 225, image: '', info:''  },
                                                                            { name: 'Pikes', parent: 'Protacanthopterygii', age: 0, image: '', info:''  },
                                                                                { name: 'Salmon', parent: 'Protacanthopterygii', age: 0, image: '', info:''  },
                                                                                { name: 'Trout', parent: 'Protacanthopterygii', age: 0, image: '', info:''  },
                                                                        { name: 'anon_7', parent: 'anon_6', unnamed: true, age: 0,  image: '', info:''  },    
                                                                        { name: 'Viperfish', parent: 'anon_7', age: 0, image: '', info:''  },
                                                                            { name: 'anon_8', parent: 'anon_7', unnamed: true, age: 0,  image: '', info:''  }, 
                                                                            { name: 'Lizardfish', parent: 'anon_8', age: 0, image: '', info:''  },
                                                                                { name: 'anon_9', parent: 'anon_8', unnamed: true, age: 0,  image: '', info:''  }, 
                                                                                { name: 'Lanturnfish', parent: 'anon_9', age: 0, image: '', info:''  },
                                                                                    { name: 'anon_10', parent: 'anon_9', unnamed: true, age: 100,  image: '', info:''  }, 
                                                                                        { name: 'Percomorpha', parent: 'anon_10', age: 0,  image: '', info:''  }, 
                                                                                            { name: 'Toadfish', parent: 'Percomorpha', age: 30,  image: '', info:''  }, 
                                                                                            { name: 'anon_12', parent: 'Percomorpha', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                { name: 'anon_14', parent: 'anon_12', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                    { name: 'gobies', parent: 'anon_14', age: 0,  image: '', info:''  },
                                                                                                    { name: 'anon_22', parent: 'anon_14', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                        { name: 'Eupercaria', parent: 'anon_22', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                            { name: 'Parrotfish', parent: 'Eupercaria', age: 0,  image: '', info:''  },
                                                                                                            { name: 'anon_23', parent: 'Eupercaria', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                { name: 'Butterflyfish', parent: 'anon_23', age: 0,  image: '', info:''  },
                                                                                                                { name: 'anon_24', parent: 'anon_23', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                    { name: 'Anglerfish', parent: 'anon_24', age: 0,  image: '', info:''  },
                                                                                                                    { name: 'anon_25', parent: 'anon_24', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                        { name: 'Ocean sunfish', parent: 'anon_25', age: 0,  image: '', info:''  },
                                                                                                                        { name: 'Pufferfish', parent: 'anon_25', age: 100,  image: '', info:''  },
                                                                                                        { name: 'anon_26', parent: 'anon_22', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                            { name: 'anon_27', parent: 'anon_26', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                { name: 'anon_28', parent: 'anon_27', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                    { name: 'Snakeheads', parent: 'anon_28', age: 0,  image: '', info:''  },
                                                                                                                    { name: 'Gouramis', parent: 'anon_28', age: 0,  image: '', info:''  }, //includes siamese fighting fish
                                                                                                                { name: 'anon_29', parent: 'anon_27', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                    { name: 'anon_30', parent: 'anon_29', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                        { name: 'Roosterfish', parent: 'anon_30', age: 0,  image: '', info:''  },
                                                                                                                        { name: 'Remora', parent: 'anon_30', age: 0,  image: '', info:''  },
                                                                                                                    { name: 'anon_31', parent: 'anon_29', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                        { name: 'Barracudas', parent: 'anon_31', age: 81,  image: '', info:''  },
                                                                                                                        { name: 'anon_32', parent: 'anon_31', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                            { name: 'Flatfish', parent: 'anon_32', age: 60,  image: '', info:''  },
                                                                                                                            { name: 'anon_33', parent: 'anon_32', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                                { name: 'Archerfish', parent: 'anon_33', age: 60,  image: '', info:''  },
                                                                                                                                { name: 'anon_34', parent: 'anon_33', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                                    { name: 'Swordfish', parent: 'anon_34', age: 3,  image: '', info:''  },
                                                                                                                                    { name: 'Marlin', parent: 'anon_34', age: 0,  image: '', info:''  }, //incl sailfish and spearfish
                                                                                                                { name: 'anon_35', parent: 'anon_26', unnamed: true, age: 66,  image: '', info:''  },
                                                                                                                    { name: 'anon_36', parent: 'anon_35', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                        { name: 'Freshwater angelfish', parent: 'anon_36', age: 0,  image: '', info:''  },
                                                                                                                        { name: 'Flying fish', parent: 'anon_36', age: 0,  image: '', info:''  },
                                                                                                                    { name: 'anon_37', parent: 'anon_35', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                        { name: 'Asiatic glassfish', parent: 'anon_37', age: 0,  image: '', info:''  },
                                                                                                                        { name: 'Clownfish', parent: 'anon_37', age: 0,  image: '', info:''  },
                                                                                                    { name: 'anon_13', parent: 'anon_12', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                        { name: 'anon_15', parent: 'anon_13', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                            { name: 'Mackerel', parent: 'anon_15', age: 0,  image: '', info:''  },
                                                                                                            { name: 'Tuna', parent: 'anon_15', age: 0,  image: '', info:''  },
                                                                                                        { name: 'anon_16', parent: 'anon_13', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                            { name: 'anon_17', parent: 'anon_16', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                { name: 'Seamoth', parent: 'anon_17', age: 0,  image: '', info:''  },
                                                                                                                { name: 'Flying gurnard', parent: 'anon_17', age: 0,  image: '', info:''  },
                                                                                                            { name: 'anon_18', parent: 'anon_16', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                { name: 'Trumpetfish', parent: 'anon_18', age: 0,  image: '', info:''  },
                                                                                                                { name: 'anon_19', parent: 'anon_18', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                    { name: 'Ghost pipefish', parent: 'anon_19', age: 0,  image: '', info:''  },
                                                                                                                    { name: 'anon_20', parent: 'anon_19', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                        { name: 'Pipefish', parent: 'anon_20', age: 0,  image: '', info:''  },
                                                                                                                        { name: 'anon_21', parent: 'anon_20', unnamed: true, age: 0,  image: '', info:''  },
                                                                                                                            { name: 'Seahorse', parent: 'anon_21', age: 0,  image: '', info:''  },
                                                                                                                            { name: 'Seadragon', parent: 'anon_21', age: 0,  image: '', info:''  },                                                                                                    
                                                                                        { name: 'anon_11', parent: 'anon_10', unnamed: true, age: 0,  image: '', info:''  }, 
                                                                                            { name: 'Lampripterygii', parent: 'anon_11', age: 0, image: '', info:''  },
                                                                                                { name: 'Oarfish', parent: 'Lampripterygii', age: 0, image: '', info:''  },
                                                                                                { name: 'Opahs', parent: 'Lampripterygii', age: 0, image: '', info:''  },
                                                                                            { name: 'Paracanthopterygii', parent: 'anon_11', age: 0, image: '', info:''  },
                                                                                                { name: 'Tube-eyes', parent: 'Paracanthopterygii', age: 0, image: '', info:''  },
                                                                                                { name: 'Cod', parent: 'Paracanthopterygii', age: 0, image: '', info:''  },





                                    
                                            { name: 'Lobe-finned fishes', parent: 'Bony fishes',rank:"clade IV", age: 425, image: 'images/guiyu_oneiros.jpg', info:'info/lobe-finned fishes.md'  },
                                                { name: 'Coelacanths', parent: 'Lobe-finned fishes', age: 420, image: 'images/coelacanth.png', info:''  },
                                                { name: 'Rhipidistia', parent: 'Lobe-finned fishes', age: 0, image: 'images/rhipidistia.jpg', info:''  },
                                                    { name: 'Lungfish', parent: 'Rhipidistia', age: 415, image: 'images/lungfish.jpg', info:''  },
                                                    { name: 'Tetrapodomorpha', parent: 'Rhipidistia', age: 409,rank:"clade V", image: 'images/tiktaalik.jpg', info:'info/tetrapodomorpha.md'},
                                                        { name: 'Tetrapods', parent: 'Tetrapodomorpha', age: 372, image: '', info:''  },
                                                            { name: 'Temnospondyls', parent: 'Tetrapods', age: 0, image: '', info:''  },
                                                                { name: 'Lissamphibia', parent: 'Temnospondyls', age: 0, image: '', info:''  },
                                                                    { name: 'Caecilians', parent: 'Lissamphibia', age: 0, image: '', info:''  },
                                                                    { name: 'Batrachia', parent: 'Lissamphibia', age: 0, image: '', info:''  }, 
                                                                        { name: 'Frogs', parent: 'Batrachia', age: 0, image: '', info:''  }, 
                                                                        { name: 'Salamanders', parent: 'Batrachia', age: 0, image: '', info:''  }, 
                                                                { name: 'Other Temnospondyls', parent: 'Temnospondyls', age: 0, image: '', info:''  }, 
                                                            { name: 'Reptiliomorpha', parent: 'Tetrapods', age: 0, image: '', info:''  }, //incl diadectomorpha
                                                                { name: 'Lemnospondyls', parent: 'Reptiliomorpha', age: 0, image: '', info:''  },        
                                                                { name: 'Amniota', parent: 'Reptiliomorpha',rank:"clade VI", age: 0, image: '', info:''  },
                                                                    { name: 'Synapsida', parent: 'Amniota',rank:"clade VII", age: 0, image: '', info:''  },
                                                                    { name: 'Sauropsida', parent: 'Amniota',rank:"clade VII", age: 316, image: '', info:''  },
                                                                        { name: 'Parareptilia', parent: 'Sauropsida', age: 306, ageEnd: 201, image: '', info:''  }, 
                                                                        { name: 'Eureptilia', parent: 'Sauropsida', age: 0, image: '', info:''  },
                                                                            { name: 'Other Reptiles', parent: 'Eureptilia', age: 314, ageEnd: 247, image: '', info:''  }, //left as a note (top age can be anywehre from 307 to 314 check it fits within parents)
                                                                            { name: 'Crown Reptiles', parent: 'Eureptilia', age: 0, image: '', info:''  },
                                                                                { name: 'Lepidosauria', parent: 'Crown Reptiles',rank:"clade VIII", age: 252, image: '', info:''  }, //check age
                                                                                { name: 'Archelosauria', parent: 'Crown Reptiles',rank:"clade VIII", age: 269, image: '', info:'info/archelosauria.md'},
                                                                                    { name: 'Pantestudines', parent: 'Archelosauria', age: 0, image: '', info:''},
                                                                                    { name: 'Archosauromorpha', parent: 'Archelosauria', age: 267, image: '', info:''},
                                                                                        { name: 'Marine reptile complex', parent: 'Archosauromorpha', age: 261, ageEnd: 66, image: '', info:''},
                                                                                            { name: 'Thalattosauria', parent: 'Marine reptile complex', age: 250, ageEnd: 212, image: 'images/thalattosaur.jpg', info:''}, //possibly slightly later (start and end)
                                                                                            { name: 'Ichthyosauromorpha', parent: 'Marine reptile complex', age: 257, ageEnd: 90, image: 'images/ichthyosaur.jpg', info:''},
                                                                                            { name: 'Sauropterygomorpha', parent: 'Marine reptile complex', age: 251, ageEnd: 66, image: 'images/sauropterygomorpha.jpg', info:'info/sauropterygomorpha.md'},
                                                                                        { name: 'CrownArchosauromorpha', parent: 'Archosauromorpha', age: 264, image: '', info:''},




        { name: 'Protostomia', parent: 'Bilateria',  rank:"superphylum", age: 558, image: '', info:'' },
            { name: 'Ecdysozoa', parent: 'Protostomia', age: 0, image: '', info:'' },
                { name: 'Penis worms', parent: 'Ecdysozoa', age: 0, image: '', info:'' },
                { name: 'nematodaIpanarthropoda', parent: 'Ecdysozoa', unnamed: true, age: 0, image: '', info:'' },
                    { name: 'Nematodes', parent: 'nematodaIpanarthropoda', age: 0, image: '', info:'' },
                    { name: 'Panarthropoda', parent: 'nematodaIpanarthropoda', age: 508, image: 'images/panarthropoda.jpg', info:'info/panarthropoda.md' },
                        { name: 'Tardigrades', parent: 'Panarthropoda', age: 500, image: 'images/tardigrade.jpg', info:'' },
                        { name: 'Antennapoda', parent: 'Panarthropoda', unnamed: true, age: 0, image: '', info:'' },
                            { name: 'Velvet Worms', parent: 'Antennapoda', age: 309, image: 'images/velvet_worm.png', info:'' },
                            { name: 'Pambdelurion', parent: 'Antennapoda', age: 521, image: 'images/pambdelurion.png', info:'' },
                                    { name: 'Anomalocaris', parent: 'Pambdelurion', age: 520, ageEnd: 499, image: 'images/anomalocaris.jpg', info:'info/anomalocaris.md' },
                                    { name: 'Arthropods', parent: 'Pambdelurion', age: 0, image: 'images/fengzhengia.jpg', info:'' }, //Fengzhengia
                                        { name: 'Chelicerates', parent: 'Arthropods', age: 519, image: 'images/chelicerates.png', info:'' },
                                            { name: 'Offacolus', parent: 'Chelicerates', age: 0, image: 'images/offacolus.png', info:'' },
                                                { name: 'Chasmataspis', parent: 'Offacolus', age: 487, image: 'images/chasmataspis.png', info:'' },
                                                    { name: 'Eurpyterids', parent: 'Chasmataspis', age: 480, ageEnd: 267, image: 'images/eurypterid.jpg', info:'' },
                                                    { name: 'Arach2', parent: 'Chasmataspis', unnamed: true, age: 0, image: '', info:'' },
                                                        { name: 'Ticks', parent: 'Arach2', age: 0, image: 'images/tick.jpg', info:'' },
                                                        { name: 'Arach3', parent: 'Arach2', unnamed: true, age: 0, image: '', info:'' },
                                                        { name: 'Horseshoe crabs', parent: 'Arach2', age: 480, image: 'images/horsesehocrab.jpg', info:'' },
                                                            { name: 'Scorpion', parent: 'Arach3', age: 435, image: 'images/scorpion.png', info:'' },
                                                            { name: 'Trigonotarbid', parent: 'Arach3', age: 420, image: 'images/trigonotarbid .png', info:'' },
                                                                { name: 'Mygalomorphae', parent: 'Trigonotarbid',unnamed: true, age: 0, image: '', info:'' },
                                                                    { name: 'Trapdoor spiders', parent: 'Mygalomorphae', age: 0, image: 'images/trapdoor_spider.jpg', info:'' },
                                                                    { name: 'Taruntulas', parent: 'Mygalomorphae', age: 0, image: 'images/tarantula.jpg', info:'' },
                                                                { name: 'Araneomorphae', parent: 'Trigonotarbid',unnamed: true, age: 0, image: '', info:'' },
                                                                //Entelegynae
                                                                    { name: 'Jumping spiders', parent: 'Araneomorphae', age: 0, image: 'images/jumping_spider.jpg', info:'' },
                                                                    { name: 'Black widows', parent: 'Araneomorphae', age: 0, image: 'images/black_widow.jpg', info:'' },
                                        { name: 'Atennulata', parent: 'Arthropods', age: 0, image: 'images/atennulata.jpg', info:'' },
                                            { name: 'Mandibulates', parent: 'Atennulata', age: 0, unnamed: true, image: 'images/mandibulates.png', info:'' },
                                                { name: 'Myriapods', parent: 'Mandibulates', age: 428, image: 'images/myriapod.jpg', info:'' }, //first animal on land?
                                                    { name: 'Centipedes', parent: 'Myriapods', age: 428, image: 'images/centipede.jpg', info:'' },
                                                    { name: 'Millipedes', parent: 'Myriapods', age: 428, image: 'images/millipede.jpg', info:'' },
                                                        { name: 'Arthropleura', parent: 'Millipedes', age: 344, ageEnd: 292, image: 'images/arthropleura.jpg', info:'' },
                                                { name: 'PanCrustacea', parent: 'Mandibulates', age: 518, image: 'images/stemPancrustacean.png', info:'' }, //hymenocaria step req?
                                                    { name: 'Multicrustacea', parent: 'PanCrustacea', age: 0, image: '', info:'' },
                                                        { name: 'Malacostraca', parent: 'Multicrustacea', age: 0, image: '', info:'' },
                                                        { name: 'Barnacles', parent: 'Multicrustacea', age: 0, image: '', info:'' },
                                                    { name: 'Allotriocarida', parent: 'PanCrustacea', age: 0, image: '', info:'' },
                                                        { name: 'Branchiopoda', parent: 'Allotriocarida', age: 0, image: '', info:'' },
                                                        { name: 'Hexapoda', parent: 'Allotriocarida', age: 0, image: '', info:'' },
                                                        
                                            { name: 'Trilobites', parent: 'Atennulata', age: 521, ageEnd: 252, image: 'images/trilobites.png', info:'' },
                                            


                                        
                                        



                                        
            { name: 'Spiralia', parent: 'Protostomia', age: 0, image: '', info:'info/Spiralia.md' },
                { name: 'Rotifers', parent: 'Spiralia', age: 0, image: 'images/rotifer.jpg', info:'' },
                { name: 'Platytrochozoa', parent: 'Spiralia', unnamed: true, age: 580, image: '', info:'' },
                    { name: 'Flatworms', parent: 'Platytrochozoa', age: 0, image: 'images/flatworm.jpg', info:'' },
                    { name: 'Lophotrochozoa', parent: 'Platytrochozoa', unnamed: true, age: 536, image: '', info:'' },
                        { name: 'True worms', parent: 'Lophotrochozoa', age: 518, image: 'images/oldworm.jpg', info:'' },
                            { name: 'Annelida1', parent: 'True worms', age: 0, unnamed: true, image: '', info:'' },
                                { name: 'Bobbit worms', parent: 'Annelida1', age: 0, image: 'images/bobbit worm.jpg', info:'' },
                                { name: 'Ragworms', parent: 'Annelida1', age: 0, image: 'images/ragworm.jpg', info:'' }, //related info node plankton worm
                            { name: 'Annelida2', parent: 'True worms', unnamed: true, age: 0, image: '', info:'' },
                                { name: 'Annelida3', parent: 'Annelida2', unnamed: true, age: 0, image: '', info:'' },
                                    { name: 'Tube worms', parent: 'Annelida3', age: 0, image: 'images/tube worms.jpg', info:'info/tube worms.md' },
                                    { name: 'Feather duster worms', parent: 'Annelida3', age: 0, image: 'images/feather duster worm.jpg', info:'' },
                                { name: 'Annelida4', parent: 'Annelida2', unnamed: true, age: 435, image: '', info:'' },
                                    { name: 'Leeches', parent: 'Annelida4', age: 0, image: 'images/leech.jpg', info:'' },
                                    { name: 'Earthworms', parent: 'Annelida4', age: 0, image: 'images/earthworm.png', info:'' },


                        { name: 'Molluscs', parent: 'Lophotrochozoa', age: 0, image: 'images/early_mollusk.png', info:'' },
                        //{ name: 'Kryptotrochozoa', parent: 'Lophotrochozoa', unnamed: true, age: 0, image: '', info:'' },
                            //{ name: 'Bryozoa', parent: 'Kryptotrochozoa', age: 0, image: '', info:'' },
                            { name: 'Brachiopoda', parent: 'Lophotrochozoa', age: 0, image: 'images/brachiopod.jpg', info:'' },





  { name: 'Plants (placeholder)', parent: 'Life (placeholder)', age: 1000, image: 'images/plant.png', info:'info/monkey.md' },
  { name: 'Orchid', parent: 'Plants (placeholder)', age: 80, image: 'images/Orchid.png', info:''},


];

export default flatData;
