// Auto-generated by generateInfoFiles.js
export const infoNodes = new Set([
  "ambulacraria",
  "animals",
  "archelosauria",
  "arthrodira",
  "bilateria",
  "echinodermata",
  "guiyu_onerios",
  "hemichordata",
  "heterostraci",
  "monkey",
  "placozoa",
  "porifera",
  "sauropterygomorpha",
  "squalomorphi",
  "stingrays",
  "tetrapodomorpha",
  "tunicates",
  "vetulicolia",
  "xenacoelomorpha"
]);
