// Auto-generated by generateInfoFiles.js
export const infoNodes = new Set([
  "ambulacraria",
  "animals",
  "bilateria",
  "echinodermata",
  "hemichordata",
  "monkey",
  "placozoa",
  "porifera",
  "xenacoelomorpha"
]);
